### ISSUE TITLE
Unhandled exception. System.UnauthorizedAccessException: Access to the path is denied

### ISSUE THREAD

**Issue by ThomasArdal** [ThomasArdal/NuPU#1]
If running in the users folder (like c:\users\me) the following error is thrown:

```
Unhandled exception. System.UnauthorizedAccessException: Access to the path 'C:\Users\thoma\Application Data' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateRelativeDirectoryHandle(ReadOnlySpan`1 relativePath, String fullPath)
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at NuPU.Program.Main(String[] args) in /home/runner/work/NuPU/NuPU/src/NuPU/Program.cs:line 37
   at NuPU.Program.<Main>(String[] args)
```

**Comment by ThomasArdal** [comment]
Fixed in 0.1.18
